# Generated by Django 5.2.6 on 2025-09-15 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventsHandler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(verbose_name='Дата создание')),
                ('plotter', models.CharField(max_length=50, verbose_name='Плоттер')),
                ('status', models.CharField(default='UNKNOWN', max_length=20, verbose_name='Статус')),
            ],
        ),
    ]
