# Generated by Django 5.2.6 on 2025-09-15 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventshandler',
            name='preview',
            field=models.ImageField(blank=True, null=True, upload_to='previews/', verbose_name='Превью'),
        ),
    ]
